export const CATEGORIES_ICONS = {
    star: '🌟',
    cardboard: '📦',
    bottle: '🍾',
    metal: '🔩',
    recycle: '♻️',
    sparkles: '✨',
    paper: '📄',
    plastic: '🧴',
    glass: '🪟',
    clothes: '👕',
    books: '📚',
    electronics: '📱',
    batteries: '🔋',
    organic: '🍏',
    furniture: '🪑',
    construction: '🧱',
    wood: '🪵',
    garden: '🌿',
}