import { IoMdClose } from 'react-icons/io'
import { IoLogOutOutline } from 'react-icons/io5'
import {
    FaCheck,
    FaCrosshairs,
    FaTimes,
    FaSearch,
    FaMapMarkerAlt,
    FaBars,
    FaPlus,
    FaAngleRight,
    FaInfoCircle,
    FaChevronLeft,
    FaChevronRight,
    FaGithub,
    FaExternalLinkAlt,
    FaHeart,
    FaShieldAlt,
    FaLeaf,
    FaUser,
    FaMapMarkedAlt,
} from 'react-icons/fa'

export const ICONS = {
    check: FaCheck,
    cross: FaCrosshairs,
    time: FaTimes,
    search: FaSearch,
    mapMark: FaMapMarkerAlt,
    bars: FaBars,
    plus: FaPlus,
    closeIcon: IoMdClose,
    arrowLeft: FaChevronLeft,
    arrowRight: FaAngleRight,
    iconCircle: FaInfoCircle,
    chevronRight: FaChevronRight,
    goOut: IoLogOutOutline,
    gitHub: FaGithub,
    externalLink: FaExternalLinkAlt,
    hartIcon: FaHeart,
    shielIcon: FaShieldAlt,
    leafIcon: FaLeaf,
    user: FaUser,
    mapMarker: FaMapMarkedAlt,
}